version: "2"

services:
  nginx:
    image: bencomtech/nginx:1.12
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - phpfpm
    volumes:
      - ./logs:/opt/bitnami/nginx/logs
      - ./dockers/nginx:/bitnami/nginx
      - ./web:/app
  phpfpm:
    image: bencomtech/php-fpm:7.1
    volumes:
      - ./web:/app
